= Building Fotorelacjonusz from the source code

:mac_specific: pass:[(<em>Mac-specific</em>)]

**This document is certainly a piece of work-in-progress.**

It is assumed that reader has some basic programming experience at least.
Some hints may be slightly inaccurate or may require adjustments specific
for the host's system.  In such case, other documentation pages may come handy,
so do continuous integration configuration.

Feedback is welcome.

== Prerequisites

1.  {mac_specific} Command line tools are not enough for compiling QuaZIP.
Install XCode, then switch to XCode's compilers.  Typically, following does
the latter:
+
[source,bash]
--------------------------------------------------------------------------------
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
--------------------------------------------------------------------------------
+
See also: https://stackoverflow.com/a/35098040/304175.

2.  Install zlib (unless you have it already, which is quite typical).
+
Note that zlib is also distributed along with Qt, and this is probably enough
if you use Qt from the online installer.
+
TODO: Precisely describe what to do on Windows.  From the old wiki: "To build on
Windows you also need to provide zlib headers in third-party directory".

3.  Obtain Qt 5.12.  Online installer is preferred, which can be downloaded from
https://download.qt.io/official_releases/online_installers/.  On Windows, prefer
MinGW toolset over MSVC.  Fotorelacjonusz seems unready to compile with
the latter one, contributions are welcome.

== Source code

[start=4]
4.  Clone this repository.  Don't forget about submodules (`--recursive`):
+
[source,bash]
--------------------------------------------------------------------------------
git clone --recursive https://github.com/skalee/fotorelacjonusz.git
--------------------------------------------------------------------------------

== API keys

[start=5]
5.  Obtain API keys for services you need.  For Imgur, see
    https://apidocs.imgur.com[Imgur docs].

6.  Prepare a `secrets.h` header file in the application's root directory.
    Use `secrets.h.example` as a template, and fill-in relevant definitions.

== Compilation (console)

NOTE: Following steps assume that Qt build tools (`qmake`, `lrelease`) are in
path.  Adjust these commands accordingly otherwise.

[start=7]
7.  Compile QuaZIP, preferably as a static library.  On my computer, some
    additional options were required as in following example.
+
[source,bash]
--------------------------------------------------------------------------------
cd <fotorelacjousz-root>/third-party/quazip
cmake -S . -DBUILD_SHARED_LIBS:BOOL=OFF
make
--------------------------------------------------------------------------------

8.  Compile QtFtp, preferably as a static library.  On my computer, some
    additional options were required as in following example.
+
[source,bash]
--------------------------------------------------------------------------------
cd <fotorelacjousz-root>/third-party/qtftp
qmake CONFIG+=staticlib CONFIG+=c++11
make
--------------------------------------------------------------------------------

9.  Build translations.
+
[source,bash]
--------------------------------------------------------------------------------
cd <fotorelacjousz-root>
lrelease fotorelacjonusz.pro
--------------------------------------------------------------------------------

10. {mac_specific} Compile application icons into `icns` file.
+
[source,bash]
--------------------------------------------------------------------------------
cd <fotorelacjousz-root>
iconutil -c icns appicon.iconset
--------------------------------------------------------------------------------

11. Build Fotorelacjonusz
+
[source,bash]
--------------------------------------------------------------------------------
cd <fotorelacjousz-root>
qmake
make
--------------------------------------------------------------------------------
+
On Windows, it may be necessary to parametrize `qmake` with
`DEFINES+=QUAZIP_STATIC`.

== Compilation (Qt Creator)

Project compiles easily in Qt Creator.  However, all compilation steps except
for "Build Fotorelacjonusz" must be either run from console, or defined as
custom build phases in Qt Creator.  Though the latter is not very difficult to
do, I am not going to describe it before I simplify it further.
Hence, for now it is recommended to build things from console.
